#baseurl: https://jamesmendel.github.io
account: jamesmendel
title: James Mendel
# subtitle: Student @ The University of Kansas
subtitle: Creative Technologist
markdown: kramdown
description: James Mendel's Website
url: https://jamesmendel.com
github: https://github.com/jamesmendel
linkedin: https://linkedin.com/in/james-mendel
currentterm: Spring 2023
