#baseurl: https://jamesmendel.github.io
account: jamesmendel
title: James Mendel
subtitle: Student @ The University of Kansas
markdown: kramdown
description: James Mendel's Website
url: http://jamesmendel.github.io
github: https://github.com/jamesmendel
linkedin: https://linkedin.com/in/james-mendel
currentterm: Spring 2021
